trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:

- stage: Build_Frontend
  jobs:
  - job: BuildReact
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'

    - script: |
        cd frontend
        npm install
        npm run build
      displayName: 'Build React App'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: 'frontend/build'
        artifactName: 'react-build'
        publishLocation: 'pipeline'

- stage: Deploy_Backend
  dependsOn: Build_Frontend
  jobs:
  - job: DeployFlask
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.10'

    - script: |
        cd backend
        pip install -r requirements.txt
        echo "Flask backend ready to deploy"
      displayName: 'Prepare Flask'

    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'test-sc'
        appType: 'webAppLinux'
        appName: 'laughApi'
        package: '$(System.DefaultWorkingDirectory)/backend'
